### ISSUE TITLE
Return x,y position of each star in a quad.

### ISSUE THREAD

**Issue by swaterfall** [Jusas/WatneyAstrometry#1]
Would it be possible to have a function that returns the x,y position of each star in a quad that can be then used to produce an image like the one below shown on the ASTAP page:

![](http://www.hnsky.org/astap_quads.jpg)

**Comment by Jusas** [comment]
Yes, actually the feature kind of already exists but is not exposed outside the library and is not included in the CLI app outputs. Drawing the quads itself would need to be implemented into the CLI solver, but is basically not a big deal as visual tests have already been coded into the unit tests.

I suppose the quad and star positions could be written into a diagnostics file with quite little effort. 
I can see more usefulness in drawing the quads as a diagnostics tool, but it's not a big deal to implement both things. I'll put this on my list.

**Comment by Jusas** [comment]
Just realized this was still open 😅 

This feature is available on the Watney Desktop, as well as possible to get and use for your own visualizations in the WatneyAstrometry.Core library via the `SolveResult.GetDiagnosticsData()` method. You can see this done in the sources, https://github.com/Jusas/WatneyAstrometry/blob/master/src/WatneyAstrometry.SolverVizTools/Drawing/Visualizer.cs

```cs
var solveResult = await solver.SolveFieldAsync(img, strategy, options, token);
var diagData = solveResult.GetDiagnosticsData();

// diagData.DetectedStars
// diagData.MatchInstances
// many things available...

var quads = solveResult.GetDiagnosticsData().FormedImageStarQuads;

foreach (var quad in quads)
{
    // With image quads we can draw lines between stars, and also a shape
    // representing the ratios.

    var points = new List<PointF>();
    foreach (var star in quad.ImageStars)
    {
        points.Add(new PointF((float)star.X, (float)star.Y));
    }

    var font = GetDefaultFont(GetQuadSymbolFontSize(solveResult));

    points.Add(new PointF(points.First().X, points.First().Y));
    var color = GenerateQuadColor((double)points.First().X, (double)points.First().Y);

    baseImage.Mutate(context =>
    {
        context.DrawLines(_defaultDrawingOptions, color, 1.0f, points.ToArray());
    });
}
```

![image](https://user-images.githubusercontent.com/5293904/213913407-b92cbfd0-7a26-47ab-b6df-ddafd6f95fe0.png)

As for the CLI app, I currently don't have big plans for visualizations.
I'm closing this issue as in a sense this feature now exists, along with an example of how this could be achieved.

But there's no real reason why it couldn't be there in the CLI app as well but since it's not a priority for me, I'm just going to say that pull requests are welcome 🚀 🙂
