### ISSUE TITLE
Error in writing WCS file

### ISSUE THREAD

**Issue by mworion** [Jusas/WatneyAstrometry#4]
Hi Jusas,

long time no see. I integrated your solver in MW4. Pretty nice work. Actually I found an issue in the resulting WCS file with solve solutions. If you get results with long numbers (strings) they don't fit to the FITS header:

Example:
```
CD2_2   = 3.4703595730434245E- / cd matrix 
```

where the entry in the json file says:
```
  "fits_cd2_2": 3.4703595730434245E-07,
``

best regards,
Michel

**Comment by Jusas** [comment]
Hi Michel! Happy to hear it's being used!

And thanks for reporting this. I'll get this fixed, looks pretty straightforward to fix.

**Comment by mworion** [comment]
I like the performance as I had ASTAP integrated, but this takes a little longer on CLI basis.
Do you know if there is the willingness to deliver and install your solver integrated with EKOS package ?

**Comment by Jusas** [comment]
> I like the performance as I had ASTAP integrated, but this takes a little longer on CLI basis. Do you know if there is the willingness to deliver and install your solver integrated with EKOS package ?

I'm not sure - I don't think they want to bundle this solver with their package, since this again requires its own build process, Watney requires its own database files and the way EKOS uses it is just like ASTAP, as its own separate process. This is after all C# / .NET code, which can't really be embedded as a library into a C++ program.

I know StellarSolver's astrometry.net version gets its speed from being inside the process, and that's hard to compete with. Of course one way would be to create a version of Watney as a "service", being ready and loaded in memory to solve any inputs it gets (kind of what the WebAPI does, but for different reasons). That might be something worth looking into.

**Comment by Jusas** [comment]
A fixed build is now available, see the latest https://github.com/Jusas/WatneyAstrometry/releases/tag/bleeding-cli

I'm assuming it works based on a successful unit test. I'll be creating a new release sometime soonish.

**Comment by Jusas** [comment]
v1.1.3 is out which should fix the issue - let me know if there are any more problems. I'm closing this issue.

**Comment by mworion** [comment]
Can confirm it's working now. Thanks for fixing.
Remark: Now I get (as I use OSx) for the first run a message that verification is needed. I don't remember that question on v1.1.2?
Michel

**Comment by Jusas** [comment]
> Can confirm it's working now. Thanks for fixing. Remark: Now I get (as I use OSx) for the first run a message that verification is needed. I don't remember that question on v1.1.2? Michel

Verification? Some sort of OSX security feature, like sometimes in Windows it asks if you want to run a downloaded executable (Windows SmartScreen or something)? It's probably something I can't control, unless I'd sign the executables which again is just more of a hassle.
