### ISSUE TITLE
  fov _view  between 10- 20 degree. which database choose ? 

### ISSUE THREAD

**Issue by taurushappy** [Jusas/WatneyAstrometry#6]
fov _view  between 10- 20 degree. which database choose ? 
 is watneyqdb-00-07-20-v3.zip?

**Comment by Jusas** [comment]
Yes, as is described here: https://github.com/Jusas/WatneyAstrometry/wiki/Quad-database-downloads
If it's not yielding results, then also grab the next one (08-09-20) and see if it helps.

However I must warn you, that field of view is getting so big that distortions may make it not possible to solve. The simple solving algorithm in Watney does not take distortions into account - in conventional, lower field of view shots the distortion is not significant enough to cause issues so it's not a problem. I've personally been solving max. 5 degrees FoV so I can't reliably say what the results are for larger fields.

**Comment by taurushappy** [comment]
thanks !  t try   the astrometry.net can solve the picture fov_view  between 10- 20 degree , is  astrometry.net can deal with the distortions  in big view_filed .
![Uploading IMG_20240215204502_664.jpg…]()
![Uploading IMG_20240215204503_676.jpg…]()

this is the file i try in attach files

**Comment by taurushappy** [comment]
![IMG_20240215204503_676](https://github.com/Jusas/WatneyAstrometry/assets/34789065/0ccb4b0b-672b-46d4-b4a8-e66c21330ffd)
![IMG_20240215204502_664](https://github.com/Jusas/WatneyAstrometry/assets/34789065/97d12c5c-00cf-40d0-bf32-954d927edc93)

**Comment by Jusas** [comment]
I'm guessing the problem here is actually the poor man's star detection algorithm that Watney has. Experiment with your exposure and filters, see if you can get more stars out of the image. Comparable fields do actually resolve in Watney, provided there is enough stars visible. It can be often trial-and-error with the exposure to get it working, sometimes longer exposures do the trick.

Perhaps at some point I'll re-visit the star detection and make it better - I also had a little FITS library side project I wanted to add to use in Watney to make the FITS support a bit better. Also had some ideas brewing in my head for further improving performance... but I've been focusing on other things in life for the past year, so I'll have to see when I find the itch to get back to this.

So: experiment with different exposure settings, see if they can help.
